### ISSUE TITLE
os.environ['KERAS_BACKEND'] 오류 문의드립니다.

### ISSUE THREAD

**Issue by hyuny223** [quantylab/rltrader#108]
keyerror KERAS_BACKEND가 뜹니다.
환경변수가 존재하지 않는 것 같은데 어떻게 해결해야 하나요?

**Comment by quantylab** [comment]
https://github.com/quantylab/rltrader/blob/master/main.py#L40

여기서 env를 설정해주고 있습니다.
main 호출 커맨드를 알려주시면 다시 확인해보겠습니다 : )

> 요즘 좀 바빠서;; 답변이 늦어졌네요... 이미 해결된 상태면 close 부탁드립니다.

**Comment by hyuny223** [comment]
확인해보도록 하겠습니다. 답변 감사합니다 :)
