### ISSUE TITLE
TF2.5에서 data폴더 v3 요청

### ISSUE THREAD

**Issue by aru001** [quantylab/rltrader#110]
TF2.5를 테스트 해볼려고 하는데 data에 v3를 사용하게 되어 있는데 소스에는 v3가 없습니다.
v3를 요청 드립니다.

**Comment by quantylab** [comment]
학습데이터 v3 공유드립니다.
http://naver.me/5eGyAzHr

암호: 5252

**Comment by aru001** [comment]
감사합니다.
