### ISSUE TITLE
보상함수 질문 있습니다.

### ISSUE THREAD

**Issue by hyuny223** [quantylab/rltrader#111]
책을 보다가 질문이 생겼는데 물어볼 곳이 없어서 여기에 질문글 올립니다!
보상함수의 정의는 s에서 a르르 취했을 때의 보상의 기대값입니다.
이때 R_t+1의 정체가 무엇인지 궁금합니다. 말로 명확하게 설명이 안 되는데, 획득보상(G)는 감가율이 적용된 보상의 합이라면, R은 감가율이 적용이 안 된 보상의 합인가요? R_t+1이 그리드에서 어떠한 방식으로 구해지는 것인지 직관적으로 와 닿지 않았습니다..
답변 기다리고 있겠습니다. 감사합니다 :)

**Comment by quantylab** [comment]
`3.6.1 몬테카를로 학습` 부분에 대한 질문으로 이해했는데 맞겠죠?

`G_t` 는 `t` 시점에서 앞으로 획득할 수 있는 보상의 합입니다. 그래서 에피소드를 끝마쳐야지 이 값을 구할 수 있습니다. 그렇다고 모든 경우의 수를 다 구할 수 없기 때문에 에피소드 n번 동안의 샘플로 이 값을 추정합니다.

책에서 써놓은 표현을 다시 보니 좀 헤깔릴 수 있겠네요...  아래 상태 가치 함수 업데이트 수식에서 `G_i`를 `i`번째 에피소드에서의 획득 보상으로 사용했기 때문에 `G_t` 대신 `G(t)`로 표현하는게 더 좋겠네요. 전반적으로 수식에 대한 설명을 보강하는 작업을 포함해서 다음 쇄를 찍을 때 수정하려 합니다.
