### ISSUE TITLE
학습 데이터에 관해 질문드립니다 (국채 관련)

### ISSUE THREAD

**Issue by romiet-jin** [quantylab/rltrader#114]
3년 국채의 X일 평균 종가 대비 당일 종가 비율을 책에 적혀 있는대로 한번 구해보려 하는데 값이 다르게 나옵니다.

import FinanceDataReader as fdr 를 한 후
rolling.mean 함수와 ewm.mean함수를 이용하여 구해봤습니다만 v2폴더에 있는 비율값과 차이가 있었습니다.

실례가 되지 않는다면 어떻게 구하셨는지 질문드려도 괜찮을까요?

**Comment by quantylab** [comment]
@romiet-jin 어떤 소스의 3년 국채 시계열을 사용하셨나요? v2 데이터는 TIGER 국채3년 시계열을 rolling.mean 한 것입니다.

**Comment by romiet-jin** [comment]
야후 파이낸스를 사용했습니다 (KR3YT=RR)
TIGER 국채의 경우 시장가격과 기준가격중 무엇을 사용하였는지도 질문드립니다.

**Comment by romiet-jin** [comment]
야후 파이낸스 사용하였습니다
TIGER 국채 3년에 두가지가 있던데 시장가격 이용하신 것이 맞으신지요?
