### ISSUE TITLE
  raise KeyError(f"{not_found} not in index")-help me

### ISSUE THREAD

**Issue by goldmarine** [quantylab/rltrader#122]
PS C:\rltrader> python main.py --stock_code 005930 --rl_method dqn --net dnn --learning --num_epoches 100 --lr 0.001 --start_epsilon 1 --discount_factor 0.9
2021-11-07 23:27:58.672136: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
Enabling eager execution
Enabling v2 tensorshape
Enabling resource variables
Enabling tensor equality
Enabling control flow v2
Disabling eager execution
Disabling v2 tensorshape
From C:\Users\goodrich\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\compat\v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Disabling resource variables
Disabling tensor equality
Disabling control flow v2
Eager Mode: False
Traceback (most recent call last):
  File "C:\rltrader\main.py", line 85, in <module>
    chart_data, training_data = data_manager.load_data(
  File "C:\rltrader\data_manager.py", line 113, in load_data
    return load_data_v3(code, date_from, date_to)
  File "C:\rltrader\data_manager.py", line 165, in load_data_v3
    scaler.fit(df[COLUMNS_TRAINING_DATA_V3].dropna().values)
  File "C:\Users\goodrich\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\frame.py", line 3030, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "C:\Users\goodrich\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\indexing.py", line 1266, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
  File "C:\Users\goodrich\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\indexing.py", line 1316, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "['foreign_ma20', 'volume_ma5_ratio', 'ind_diff', 'bond_k3y_ma20_ratio', 'volume_lastvolume_ratio', 'foreign_diff', 'ind_ma120', 'volume_ma10_ratio', 'inst_ma20', 'ind_ma5', 'foreign_ma60', 'inst_ma10', 'foreign_ma120', 'inst_ma5', 'close_ma10_ratio', 'inst_diff', 'ind', 'volume_ma60_ratio', 'low_close_ratio', 'ind_ma20', 'bond_k3y_ma5_ratio', 'close_ma5_ratio', 'volume_ma120_ratio', 'bond_k3y_ma60_ratio', 'high_close_ratio', 'diffratio', 'close_ma20_ratio', 'ind_ma10', 'bond_k3y_ma120_ratio', 'inst', 'ind_ma60', 'close_ma60_ratio', 'open_lastclose_ratio', 'inst_ma120', 'close_ma120_ratio', 'foreign_ma5', 'foreign_ma10', 'volume_ma20_ratio', 'foreign', 'inst_ma60'] not in index"
PS C:\rltrader>

**Comment by Gentlyweep** [comment]
> PS C:\rltrader> python main.py --stock_code 005930 --rl_method dqn --net dnn --learning --num_epoches 100 --lr 0.001 --start_epsilon 1 --discount_factor 0.9 2021-11-07 23:27:58.672136: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll Enabling eager execution Enabling v2 tensorshape Enabling resource variables Enabling tensor equality Enabling control flow v2 Disabling eager execution Disabling v2 tensorshape From C:\Users\goodrich\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\compat\v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version. Instructions for updating: non-resource variables are not supported in the long term Disabling resource variables Disabling tensor equality Disabling control flow v2 Eager Mode: False Traceback (most recent call last): File "C:\rltrader\main.py", line 85, in chart_data, training_data = data_manager.load_data( File "C:\rltrader\data_manager.py", line 113, in load_data return load_data_v3(code, date_from, date_to) File "C:\rltrader\data_manager.py", line 165, in load_data_v3 scaler.fit(df[COLUMNS_TRAINING_DATA_V3].dropna().values) File "C:\Users\goodrich\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\frame.py", line 3030, in **getitem** indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1] File "C:\Users\goodrich\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\indexing.py", line 1266, in _get_listlike_indexer self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing) File "C:\Users\goodrich\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\indexing.py", line 1316, in _validate_read_indexer raise KeyError(f"{not_found} not in index") KeyError: "['foreign_ma20', 'volume_ma5_ratio', 'ind_diff', 'bond_k3y_ma20_ratio', 'volume_lastvolume_ratio', 'foreign_diff', 'ind_ma120', 'volume_ma10_ratio', 'inst_ma20', 'ind_ma5', 'foreign_ma60', 'inst_ma10', 'foreign_ma120', 'inst_ma5', 'close_ma10_ratio', 'inst_diff', 'ind', 'volume_ma60_ratio', 'low_close_ratio', 'ind_ma20', 'bond_k3y_ma5_ratio', 'close_ma5_ratio', 'volume_ma120_ratio', 'bond_k3y_ma60_ratio', 'high_close_ratio', 'diffratio', 'close_ma20_ratio', 'ind_ma10', 'bond_k3y_ma120_ratio', 'inst', 'ind_ma60', 'close_ma60_ratio', 'open_lastclose_ratio', 'inst_ma120', 'close_ma120_ratio', 'foreign_ma5', 'foreign_ma10', 'volume_ma20_ratio', 'foreign', 'inst_ma60'] not in index" PS C:\rltrader>

Do u fix it？I meet the same error
