### ISSUE TITLE
기간 필터링 수정 시 발생 에러 질문

### ISSUE THREAD

**Issue by sdragoonj** [quantylab/rltrader#29]
안녕하세요. 좋은 책 잘 읽고 있고, 미흡하지만 조금씩 배워나가고 있습니다.

질문은 제목처럼 기간 필터링 수정 시 발생하는 에러 문제인데요

기간을 늘리거나, 혹은 과거의 특정 기간을 학습하고 싶어서

예를들어, 아래와 같은 기간으로 설정을 실시하여 Run을 시켰을때,

-------------------------------------------------------------------------------
training_data = training_data[(training_data['date'] >= '2015-09-23') &
                                  (training_data['date'] <= '2015-10-14')]
-------------------------------------------------------------------------------

아래와 같은 에러가 발생합니다.

-------------------------------------------------------------------------------
 File "D:/rltrader-master/rltrader-master/main_custom.py", line 63, in <module>
    discount_factor=0, start_epsilon=.5)
  File "D:\rltrader-master\rltrader-master\policy_learner.py", line 178, in fit
    initial_balance=self.agent.initial_balance, pvs=memory_pv
  File "D:\rltrader-master\rltrader-master\visualizer.py", line 63, in plot
    self.axes[2].plot(x, outvals[:, action], style)
IndexError: too many indices for array
-------------------------------------------------------------------------------

여러 원인을 상상하여 혼자 힘으로 찾아보려는데 잘 되지 않아서 질문을 남깁니다.

답변 기다리겠습니다. 감사합니다.

**Comment by quantylab** [comment]
@sdragoonj 답변이 늦었네요...
out of index 에러로 보이는데 axes의 size, outvals의 shape를 확인해 봐야 원인을 알 수 있을 것 같습니다.
IDE를 사용하고 계시다면 에러가 나는 줄에 breakpoint를 찍고 확인해 보시길 권해드립니다.

**Comment by sdragoonj** [comment]
안녕하세요. 
말씀해 주신것 처럼 Error가 나는 줄 앞에 breakpoint()를 하고
-------------------------------------------------------------------------------
        breakpoint()
        for action, style in zip(action_list, styles):
            # 정책 신경망의 출력을 빨간색, 파란색 점으로 그리기
            self.axes[2].plot(x, outvals[:, action], style)
-------------------------------------------------------------------------------
np.size(self.axes)
np.size(self.axes[2])
np.shape(outvals)
의 결과 각각 4, 1, 및 (0, ) 나왔습니다.

이는 정상동작하는 아래와 같은 예시 기간에서의
-------------------------------------------------------------------------------
    training_data = training_data[(training_data['date'] >= '2017-01-23') &
                                  (training_data['date'] <= '2017-12-14')]
-------------------------------------------------------------------------------
np.size(self.axes)
np.size(self.axes[2])
np.shape(outvals)
의 결과 각각 4,1, 및(219,2) 와는 다른 양상입니다.

말씀해 주신것처럼 outvals가 (0, )이 나오는것이 문제 같아 보이는데
혹시 도움을 청할 수 있을까요?

**Comment by sdragoonj** [comment]
안녕하세요. 문제를 계속 찾아가는 도중 에러가 발생하는 기간에서는
training_data에 데이터가 들어가지 않는 현상 때문임을 확인했습니다.
더 확인 후 결과 나오면 공유 드리겠습니다.

**Comment by sdragoonj** [comment]
제가 작성한 문제는 main.py 가 아닌 main_custom.py 에서 발생합니다.
그리고 main_custom.py가 사용하는 data_manager_custom에서 일정 기간을 처리하지 못하는 문제로
계속 나오고 있다 추측됩니다.

inst, 및 frgn을 일정기간에서는 받아오지 못하는지
prep_data는 생성되지만 training_data는 생성되지 않습니다.

**Comment by sdragoonj** [comment]
제가 제 나름의 방법으로 이상한 부분을 해결한 것에 대해 말씀을 드리겠습니다.
제가 코드도 이제 막 배우고 있고 잘 모르기 때문에 유추한 내용이 대부분 입니다.
이점 양해 부탁드리겠습니다.
그리고 추가 의견 있으시면 부탁드리겠습니다.

책의 마지막 커스터마이징 부분에서 '주식 데이터 읽기 커스터마이징' 챕터의 경우
학습을 시작하는 첫 시점이 기관과 외인 부분 데이터가 생기는 시점 + 약 6개월 이후 부터입니다.
이유는 window 때문으로 유추가되지만 120 개의 데이터가 모였을 때부터 학습을 시작함을 확인하였습니다.

추가적으로 커스터마이징 부분에서 기관과 외인의 정보가 없을시  nan으로 바꾸게 되는데 이 부분의 csv 데이터를 강제로 빈칸이 아닌 '0'으로 바꾸게 했더니 기관과 외인의 정보가 생기기 시작하는 첫 시점부터 학습을 시작해 나가는 모습을 볼 수 있었습니다.

이러한 내용에 대해 읽고 의견 주시면 정말로 감사하겠습니다.
이상입니다. 감사합니다.

**Comment by quantylab** [comment]
@sdragoonj 잘 확인해 주셨네요 : )
처음 120개에서 비어있는 데이터가 있는 이유는 Moving Average 120 데이터가 피처로 존재하기 때문입니다.
빈칸을 0으로 바꾸신 것은 fillna(0)을 하신 것인데요, ma20 자질이 제대로 fitting 되지 않을 수 있어서 dropna()를 하시는 것이 더 좋을 것 같습니다.

**Comment by sdragoonj** [comment]
네 감사합니다. 앞으로 좋은 기회로 다시 접하길 기대하겠습니다.
언제나 성공하세요. :)
