### ISSUE TITLE
책개정판에대한 질문입니다.

### ISSUE THREAD

**Issue by mystic4** [quantylab/rltrader#39]
책개정판은 언제쯤 출간될 예정인가요? 바쁘시더라도 답변해주시면 감사하겠습니다.
                                                                                             

                                                                                             -개정판을 간절히 기다리고있는 독자올림-

**Comment by quantylab** [comment]
@mystic4 안녕하세요 : ) RLTrader에 관심가져 주셔서 감사합니다. 개정판은 상반기 중에 출간 예정입니다. 5월 정도로 예상하고 있습니다.

**Comment by mystic4** [comment]
감사합니다

**Comment by quantylab** [comment]
개정판 출간되어 close 합니다. 감사합니다.

**Comment by kimdohyun-0** [comment]
넵
