### ISSUE TITLE
테스트시 --net 파라미터 설정에 대한 질문입니다. 

### ISSUE THREAD

**Issue by jaylee4274** [quantylab/rltrader#49]
안녕하세요 ! 질문 드립니다. 
모델 활용시, 테스트때 사용한 신경망 타입(--net)과 동일하게 커맨드를 넣는게 맞나요? \
동일 데이터로 각기 다른 신경망 dnn cnnn lstm 을 이용해 학습했는데 
모델 활용시에는 --net lstm 에서만 실행이 되는 증상을 발견했습니다.

혹시 제가 잘못 돌린 부분이 있으면 알려주시면 정말 감사드리겠습니다.
항상 답변주셔서 감사합니다. 

1. cnn으로 학습한 모델 --net cnn 적용 테스트시 
`#TestDQN
!python main.py --stock_code 005930 --net cnn --rl_method dqn --output_name test_005930 --num_epoches 1 --start_epsilon 0 --start_date 20190101 --end_date 20191231 --reuse_models --value_network_name dqn_cnn_value_005930`
![image](https://user-images.githubusercontent.com/53852714/78503694-36bdbb80-77a3-11ea-9df6-2e2464c79e3c.png)

2. dnn으로 학습한 모델 --net dnn 적용 테스트시 
`#TestDQN
!python main.py --net dnn --stock_code 005930 --rl_method dqn --output_name test_005930 --num_epoches 1 --start_epsilon 0 --start_date 20190101 --end_date 20191231 --reuse_models --value_network_name dqn_dnn_value_005930`
![image](https://user-images.githubusercontent.com/53852714/78504259-e0eb1280-77a6-11ea-8977-cfb94f26127f.png)

**Comment by quantylab** [comment]
@jaylee4274 모델 경로에 이슈가 있는듯 한데... 제 환경에서 재현이 안되어 정확히는 모르겠네요...
이슈 올리신지 오래되었는데 여전히 이슈가 있으시면 재현 상황을 좀더 알려주시고 이미 해결된 건이면 close 부탁드립니다.
