### ISSUE TITLE
76페이지 agent.py 소스 61번 라인 수정 요청 드립니다.

### ISSUE THREAD

**Issue by mrchaos** [quantylab/rltrader#5]
self.num_hold 를 self.num_stocks으로 변경하는 것이 옳을거 같습니다.

수정전
self.ratio_hold = self.num_hold / int(
            self.portfolio_value / self.environment.get_price())

수정후
self.ratio_hold = self.num_stocks/ int(
            self.portfolio_value / self.environment.get_price())

**Comment by quantylab** [comment]
@mrchaos 
버그 발견 감사합니다. 수정했습니다.
