### ISSUE TITLE
Monkey Trader 구현방법에 대해서 

### ISSUE THREAD

**Issue by jaylee4274** [quantylab/rltrader#51]
학습을 진행할 수록 탐험 비율 감소 부분을 1로 고정하고 나머지를 비활성화 해서 구현해봤는데, 무작위적인 매매를 하고 있는것 같은 결과가 나오지 않아서 질문드립니다. 

혹시 MT는 어떻게 구현하셨나요? 소스코드를 공개해주시면 정말 감사하겠습니다
![image](https://user-images.githubusercontent.com/53852714/81695852-25e91f80-949e-11ea-9bd8-a79b7bb85227.png)

**Comment by quantylab** [comment]
--learning 옵션을 주지 않으면 다음 코드에서 탐험률 `epsilon`이 `start_epsilon` 값으로 지정됩니다.
```py
            # 학습을 진행할 수록 탐험 비율 감소
            if learning:
                epsilon = start_epsilon \
                    * (1. - float(epoch) / (num_epoches - 1))
                self.agent.reset_exploration()
            else:
                epsilon = start_epsilon
```

`--learning` 옵션을 주지 않고 `--start_epsilon 1`을 주시면 됩니다.

**Comment by jaylee4274** [comment]
답변 감사드립니다 !!!
