### ISSUE TITLE
v1 으로 하면 ‘close’ KeyError 가 납니다

### ISSUE THREAD

**Issue by bluesaturn1** [quantylab/rltrader#53]
개정판을 읽고 있습니다. 
예제로 들어있는 v1과 v2의 csv 파일이 달라서 그런지 (v1은 header가 없구요, v2는 헤더가 있습니다) 
v1으로 실행하면 close가 없다고 KeyError가 납니다
두가지 버전이 모두 실행되게 하려면 어떻게 고치면 될까요?
 
임시로

```
def load_data(fpath, date_from, date_to, ver):
    header = None if ver == 'v1' else 0
    data = pd.read_csv(fpath, thousands=',', header=header, 
        converters={'date': lambda x: str(x)})

    if ver == 'v1':
        data.columns = ['date', 'open', 'high', 'low', 'close', 'volume']
```

로 바꿔서 하고 있습니다.

**Comment by quantylab** [comment]
@bluesaturn1 네넵 v1은 fade out 예정이니 비슷하게 대응코드를 넣을까 합니다.
다른 수정하신 부분이 있다면 Pull Request 주시면 검토후 바로 코드 적용할 수 있을 것 같습니다.
감사합니다 : )

**Comment by quantylab** [comment]
https://github.com/quantylab/rltrader/commit/da60641eb67ccd5262e22b6b9975de1c631607e3

픽스하여 이슈 닫겠습니다. 감사합니다.
