### ISSUE TITLE
q_sample의 초기화

### ISSUE THREAD

**Issue by sdmadmin** [quantylab/rltrader#54]
개정판 코드 내용에 관한 문의사항입니다
run() 함수의 while문 블록에서 저장된 q_sample의 데이터들은 memory 변수에 저장되고  언제 초기화가 되는 것인지 궁금하네요.
memory변수들에 q_sample 데이터를 저장하고 q_sample이 다시 신규 샘플들을 받을 때, q_sample에 있는 기존 샘플들을 지우지 않으면 신규 샘플 하나만 추가되도 num_stemps 개수(=2이상일 경우)가 충족되어 q_sample에 남아있는 기존 샘플들이 중복되어 memory에 저장되는 것이 아닌지 궁금하네요. 제가 잘못 알고 있는 것인가요 ?

**Comment by quantylab** [comment]
@sdmadmin 
sample은 하나의 timepoint(여기서는 1일)에 대한 observation 입니다.
num_steps가 2라면 처음 관측했을 때는 step이 충족되지 않아서 prediction을 진행할 수 없고 두번째 관측부터 prediction이 가능하겠습니다.
q_sample의 크기를 num_steps로 정하기 때문에 세 번째 관측값이 들어오면 맨 처음의 관측값은 제거됩니다. (큐 자료구조 입니다.)
그리고 q_sample은 epoch 초기에 초기화하고 있습니다.

답변이 되셨을지 모르겠네요... 더 궁금하신 사항 있으시면 추가 커멘트 남겨주세요. 감사합니다.

**Comment by sdmadmin** [comment]
답변 감사합니다. 그런데 말씀하신대로 세 번째 관측값이 들어오면 맨 처음 관측값만 제거되고 두 번째 관측값은 그대로 유지된다면 두 번째 관측값은 두번의 prediction이 발생하고 그 결과값이 memory에 중복 저장되는 것이 아닌가요 ? num_steps를 크게 해보니 **epoch 타임이 매우 길어지는** 현상이 발생하더라구요. 아마도 관측값들이 중복으로 prediction과정을 거쳐서 그런 것이 아닌가 생각했었습니다.   그래서 q_sample은 epoch초기에 초기화가 이루어지면 안되고 while문 초기에 초기화가 이루어져야 하는 것이 아닌가 생각되어서 문의드렸습니다. ^^
추가로 궁금한 사항은 num_steps가 3일 경우 predict() 매소드가 q_sample을 인자로 받으면 각각의 샘플에 대한 예측값을 3개로 반환하여 pred_value나 pred_policy 변수에 각각 3개씩 저장하게 되는 것인가요 ? 변수를 출력 해보니 q_sample당 하나의 예측값만 반환하는 것 같아서 문의드립니다.

**Comment by quantylab** [comment]
@sdmadmin num_steps를 크게 잡으면 그만큼 입력의 크기가 커져서 처리비용이 커질 것입니다.
추가 문의에 답을 드리자면 q_sample은 그 자체가 하나의 모델 입력값이 됩니다.  모델이 q_sample을 입력 받으면 하나의 출력값을 줍니다.

실험하시다가 보다 효율적인 방식을 고안하시면 공유(Pull Request) 해주시면 감사하겠습니다 : )

**Comment by sdmadmin** [comment]
답변해 주셔서 감사합니다

**Comment by sdmadmin** [comment]
보내주신 답변에 대한 궁금증이 생겨서요 
q_sample은 그 자체가 하나의 모델 입력값이 되어 하나의 출력값을 준다고 하셨는데,
q_sample내에 있는 개별 샘플들에 대한 예측값들이 하나의 출력값에 합산(?)된 것이라고 이해하면 되는 것인가요 ?
코딩 초보라서 이것 저것 궁금한 것이 많네요 ^^

**Comment by quantylab** [comment]
@sdmadmin 현 구조에서는 q_sample 내의 개별 샘플들이 합쳐져서 모델의 입력이 되기 때문에 개별 샘플의 출력 합산이라고 보기는 어렵습니다. 개별 샘플을 입력으로 모델을 학습하고 N개의 연속된 샘플들의 출력을 합산해서 행동을 결정하는 것도 실험이 필요하겠지만 충분히 가능해 보입니다.
