### ISSUE TITLE
저장된 모델 파일의 크기와 관련하여

### ISSUE THREAD

**Issue by sdmadmin** [quantylab/rltrader#56]
q_sample관련하여 LSTM신경망의 num_steps 개념을 정확히 이해하지 못한 상황에서 질문을 드렸음에도 친절하게 답변해 주셔서 많은 도움이 되었고 이에 감사드립니다. 덕분에 많은 공부가 된 것 같습니다.

아울러 또 한가지 궁금한 사항이 있어서 다시 문을 두드립니다.

인자값을 변경하고 학습을 완료한 후 저장된 모델의 파일 크기를 확인하니 모두 동일한 크기를 갖는다는 것을 확인하였습니다.
예를들면,
A2C강화학습 진행시, EPOCH(100에서 1000까지)를 변경하여도 policy와 value 파일의 크기는 각각 2,247,649byte입니다. 
A3C강화학습 진행시에는 다른 인자들은 고정시키고 EPOCH(10에서 200까지)와 종목수(1종목에서 3종목 사이)까지 변경하였음에도 policy와 value 파일 각각의 크기가 2,247,640byte로 같습니다. 오히려 A2C의 파일크기가 A3C파일 크기보다 약간 더 큽니다.

epoch를 늘리거나 종목수가 늘어나면 학습량이 늘어나서 모델의 파일 크기가 커지는 줄 알았는데 그렇지가 않더군요. 이와같은 현상이 정상적인 것인가요 ? 책을 찾아봐도 관련된 설명이 없어서 다시 찾아뵙게 되었습니다.

**Comment by quantylab** [comment]
@sdmadmin 모델의 크기는 모델을 구성하는 퍼셉트론의 수와 비례할 것입니다. epoch가 커져도 모델을 구성하는 퍼셉트론들의 weight가 달라지는 것이고 모델의 크기가 커지거나 하지는 않을 것 같습니다. A2C와 A3C의 모델 아키텍처가 동일하지 않다면 파일 크기도 차이가 있겠습니다. 감사합니다 : )

**Comment by sdmadmin** [comment]
잘 알겠습니다. 
답변해 주셔서 감사합니다 👍 
좋은 저녀되시기 바랍니다
