### ISSUE TITLE
자동주문문의

### ISSUE THREAD

**Issue by Mystic-Pudding** [quantylab/rltrader#57]
현재 개정전인 2쇄버전 책을 읽고있는데요, 인공지능을 사용하여 종목을 분석한 다음에 증권사에서 제공해주는 api를 사용하여 자동주문까지 하고싶은데, 증권사 api는 32bit파이썬환경에서 동작하고 이 책에서다루는 인공지능인 tensorflow는 64비트 파이썬환경에서 동작하여 호환성이 맞지 않는데, 어떻게 해결하면 좋을까요?

**Comment by quantylab** [comment]
@mystic4 
각각을 시스템화 하고 Socket, HTTP 등의 방식으로 통신해야 할 둣 합니다. Kafka와 같은 플랫폼을 사용하는 것도 방법이겠습니다.
