### ISSUE TITLE
[질문] agent.py에서 decide_action 메소드의 "confidence"에 대한 질문

### ISSUE THREAD

**Issue by mrchaos** [quantylab/rltrader#7]
agent.py :: decide_action() 에서 
confidence = 1 + probs[action] 로 되어 있어
confidence는 항상 1 보다 큽니다.
그러면 
agent.py :: decide_trading_unit() 에서
added_traiding = max(min(
            int(confidence * (self.max_trading_unit - self.min_trading_unit)),
            self.max_trading_unit-self.min_trading_unit
        ), 0)
에서
min( int(confidence * (self.max_trading_unit - self.min_trading_unit)), self.max_trading_unit-self.min_trading_unit )
항상 (self.max_trading_unit-self.min_trading_unit ) 만 선택 되어 "added_traiding" 이 동적으로 바뀌지 않습니다.
수정이 필요 할거 같습니다.

**Comment by quantylab** [comment]
@mrchaos 
네 맞습니다. 학습데이터의 레이블을 [-1, 1] 범위로 사용했을 때의 구현인데 현재는 레이블 범위를 [0, 1]로 사용하고 있으므로 수정이 필요하겠습니다.

감사합니다.

**Comment by quantylab** [comment]
이 이슈는 다음 커밋으로 픽스했습니다.
https://github.com/quantylab/rltrader/commit/a6f50ac1af2fb396bfe4474ab3e23f2a2822a3b1

**Comment by quantylab** [comment]
추가로 학습데이터의 레이블과 무관하게 정책신경망의 출력층의 활성화 함수에 의존적으로 이 코드를 관리해야 하겠습니다.
현재는 출력층의 활성화 함수가 sigmoid로 되어 있으므로 출력이 [0, 1]의 범위를 가지는데, tanh 등의 음수 값이 나올 수 있는 활성화 함수를 사용한다면 출력값을 사용하는 코드 부분을 다 재검토 해야 할 것입니다.
