### ISSUE TITLE
데이터 오류 질문있습니다

### ISSUE THREAD

**Issue by ozingmw** [quantylab/rltrader#79]
data파일에 있는 데이터 외에 개인적으로 csv파일을 만들어서 실행을 하고 있는중 오류가 생겨 질문합니다.
이전 질문 목록에서 같은 질문이 나와 그 질문과 답변글을 참고하여 수정하고 다시 실행해봐도 이상하게 오류가 생겨 질문합니다.

main.py실행
`python main.py --stock_code 005930 --rl_method a2c --net lstm --num_steps 10 --output_name test_20210118_052400 --num_epoches 1 --start_epsilon 0 --start_date 20210114 --end_date 20210115 --reuse_models --value_network_name a2c_lstm_value_20210115_052400 --policy_network_name a2c_lstm_policy_20210115_052400`

실행오류
> File "main.py", line 102, in <module>
    min_trading_unit = max(int(100000 / chart_data.iloc[-1]['close']), 1)
  File "C:\Users\SJH\anaconda3\envs\ftb\lib\site-packages\pandas\core\indexing.py", line 894, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "C:\Users\SJH\anaconda3\envs\ftb\lib\site-packages\pandas\core\indexing.py", line 1500, in _getitem_axis
    self._validate_integer(key, axis)
  File "C:\Users\SJH\anaconda3\envs\ftb\lib\site-packages\pandas\core\indexing.py", line 1443, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

이런 오류입니다. 
https://github.com/quantylab/rltrader/issues/67 와 같은 오류라고 생각하여 data형식이나 오류가 없는지 확인하였지만 찾아내지 못했습니다.
제가 만든 csv데이터는 v2에 있는 csv와 동일하게 했다고 생각합니다.
[005930_1.zip](https://github.com/quantylab/rltrader/files/5829862/005930_1.zip)

정확하게 측정하지 않았지만 데이터가 적을 때 위와 같은 오류가 발생합니다. 
하지만 여기서 특이한점은 csv에 포함된 데이터가 많을 경우 오류없이 실행이 잘 됩니다..

데이터가 많은 csv
[005930_2.zip](https://github.com/quantylab/rltrader/files/5829875/005930_2.zip)
이 csv파일로 같은 main.py를 실행할 때는 오류없이 실행이 됩니다.

감사합니다.

**Comment by quantylab** [comment]
@ozingmw 

우선 데이터 크기가 너무 적은것 같습니다.  `main`에서 `data_manager.load_data()`를 호출할 것이고 이 함수는 다시 `data_manager.preprocess()` 함수를 호출합니다. 여기서 moving average 자질들을 추출하게 되는데 가장 큰 window 크기가 120이므로 적어도 240개 이상의 데이터 row가 있는게 좋습니다.

이 부분이 정확한 오류 원인인지는 모르겠지만 한번 살펴보시면 좋을 것 같습니다.

**Comment by ozingmw** [comment]
답변 감사합니다.
날짜에만 신경쓰고 오류나는 위치가 `main`에서 `min_trading_unit = max(int(100000 / chart_data.iloc[-1]['close']), 1)` 이 부분이여서 간단한걸 놓친거같습니다.
데이터도 120개 이상으로 설정하니 기간을 짧게해도 잘 실행됩니다.
감사합니다.
