### ISSUE TITLE
main.py 실행 

### ISSUE THREAD

**Issue by heunwoo3** [quantylab/rltrader#96]
안녕하세요 저서를 사서 따라해보고 있는 사람입니다. 머신러닝 입문체험을 해보고 싶어 재밌어 보이는 책을 사서 해보는데 너무 어렵네요 선생님께서 도와주실수있으실련지요
python main.py --stock_code 005930 --rl_method a2c --net lstm --num_steps 5 --output_name 005930 --learning --num_epoches 1000 --lr 0.001 --start_epsilon 1 --discount_factor 0.9 이렇게 변경한다면
if name == 'main':
parser = argparse.ArgumentParser()
parser.add_argument('005930', nargs='+')
parser.add_argument('--ver', choices=['v1', 'v2'], default='v2')
parser.add_argument(' a2c',
choices=['dqn', 'pg', 'ac', 'a2c', 'a3c', 'monkey'])
parser.add_argument('lstm ',
choices=['dnn', 'lstm', 'cnn', 'monkey'], default='dnn')
parser.add_argument('5', type=int, default=1)
parser.add_argument('--lr', type=float, default=0.01)
parser.add_argument('--discount_factor', type=float, default=0.9)
parser.add_argument('--start_epsilon', type=float, default=0)
parser.add_argument('--balance', type=int, default=10000000)
parser.add_argument('--num_epoches', type=int, default=100)
parser.add_argument('--delayed_reward_threshold',
type=float, default=0.05)
parser.add_argument('--backend',
choices=['tensorflow', 'plaidml'], default='tensorflow')
parser.add_argument(' 005930', default=utils.get_time_str())
parser.add_argument('--value_network_name')
parser.add_argument('--policy_network_name')
parser.add_argument('--reuse_models', action='store_true')
parser.add_argument('--learning', action='store_true')
parser.add_argument('--start_date', default='20170101')
parser.add_argument('--end_date', default='20171231')
args = parser.parse_args()

이런식으로 바꾸어 주는게 맞을까요? argparse.이 함수를 어떻게 사용하는지 모르겠네요.main.py에서 nargs, choices,default 이런 부분들이 ide에서 빨간 글짜로 떠서 여러가지 눌러보는데 왜 빨간글씨로 뜨는지 모르겠네요 ㅜㅜ
디폴트설정이있는 부분들은 파라미터값을 안거드려도 되는거 맞을까요?아나콘다 설치후에 파라미터 값 변경없이
conda create -n rltrader python=3.6
conda activate rltrader
pip install tensorflow-gpu==1.15
conda install cudatoolkit=10.0
conda install cudnn=7.3.1
pip install numpy
pip install pandas
from tensorflow.keras.models import Model
ModuleNotFoundError: No module named 'tensorflow'

텐서플로우 모듈이 없다는 오류가뜨네요 구글링해서 아나콘다 관리자 권한으로 실행후 다시 텐서플로우 1.15
설치해도 오류 변화가 없네요 어디서 부터 잘못 된걸까요 ㅠㅠide는 파이참 사용중인데 바로 main.py 를 파라미터값만 바꿔서 돌려주면 출력값을 얻을수있는거 맞을까요? 책을사고 한달동안 틈틈히 시도하는데 아직도 못돌려보고 있네요 ㅠㅠ

**Comment by heunwoo3** [comment]
이후에 아나콘다 재설치후 파라미터 값 변경없이 
conda create -n rltrader python=3.6
conda activate rltrader
pip install tensorflow-gpu==1.15
conda install cudatoolkit=10.0
conda install cudnn=7.3.1
pip install numpy
pip install pandas 
다시 이 가상환경 셋팅으로 main.py를 돌려보니

**Comment by heunwoo3** [comment]
그리고 파타미터 값들  변경 방식 설명도 부탁드립니다  위에 제가 한 방법대로 하면  되는게 맞는지요?

**Comment by yanmei-2020** [comment]
총체적 난국으로 보입니다...환경설정에 문제가 있을 것 같네요..설치한 환경내에서 코드를 돌리고 있는지 확인해 보면 좋을 것 같습니다. default 값을 0.9로 바꾸어준 것은 문제가 없을 것 같습니다.
